<?php

use Drupal\darts\Game;
use Drupal\darts\Player;

/**
 * @file
 * Primary module hooks for darts module.
 *
 * @DCG
 * This file is no longer required in Drupal 8.
 * @see https://www.drupal.org/node/2217931
 */

/**
 * Implements hook_theme().
 * 
 * Register a module or theme's theme implementations.
 * The implementations declared by this hook specify how a particular render array is to be rendered as HTML.
 * 
 * See: https://api.drupal.org/api/drupal/core%21lib%21Drupal%21Core%21Render%21theme.api.php/function/hook_theme/8.2.x
 * 
 * If you change this method, clear theme registry and routing table 'drush cc theme-registry' and 'drush cc router'.
 */
function darts_theme($existing, $type, $theme, $path) {

  return [      
    'counter' => [
      'render element' => 'children',
      'template' => 'counter',
      'variables' => [
        'player_selector' => null,
      ],
    ],
    'double' => [
      'render element' => 'children',
      'template' => 'double',
      'variables' => [
        'player_selector' => null,
      ],
    ],
    'chart' => [
      'render element' => 'children',
      'template' => 'chart',
      'variables' => [
        'scoreboard' => null,
        'stats' => null,
        'weights' => null,
        'date_from' => null,
        'date_to' => null,
        'players' => null,
      ],
    ],
    'generalstat' => [
      'render element' => 'children',
      'template' => 'generalstat',
      'variables' => [
        'stats' => null,
      ],
    ],
    'where' => [
      'render element' => 'children',
      'template' => 'where',
      'variables' => [
        'path' => null,
      ],
    ],
    'game' => [
      'render element' => 'children',
      'template' => 'game',
      'variables' => [
        'player_selector_a' => null,
        'player_selector_b' => null,
        'drawid' => 0,
        'path' => null,
      ],
    ],
    'gamedata' => [
      'render element' => 'children',
      'template' => 'gamedata',
      'variables' => [
        'path' => null,
        'day_selector' => null,
        'date' => null,
        'games' => null,
        'firstnines' => null,
        'highlights' => null,
        'checkouts' => null,
        'matrix' => null,
        'tree' => null,
      ],
    ],
    'gamedraw' => [
      'render element' => 'children',
      'template' => 'gamedraw',
      'variables' => [
        'teams' => null,
        'matchstatuses' => null,
        'allplayers' => null,
        'drawid' => null,
        'path' => null,
      ],
    ],
    'personalstat' => [
      'render element' => 'children',
      'template' => 'personalstat',
      'variables' => [
        'sums' => null,
      ],
    ],
  ];
}

function darts_get_last_gameid($uid) {
    $database = \Drupal::database();
    $query = $database->select('darts', 'd');
    $query
    ->fields('d', array('gameid'))
    ->condition('d.uid', $uid)
    ->orderBy('d.gameid', 'DESC')
    ->range(0, 1);

    $results = $query->execute()->fetchAll();

    return $results;
}

function darts_write_score($uid, $gameid, $score) {
    $database = \Drupal::database();
    $result = $database->insert('darts')
      ->fields([
        'uid' => $uid,
        'gameid' => $gameid,
        'score' => $score,
        'created' => \Drupal::time()->getRequestTime(),
      ])
    ->execute();

    return $result;
}

function darts_delete_score($id) {

    // TODO: for security reasons
    // delete only if record is not older than 30min
    // its not realistic for delete records in the past as its a function for undo

    $database = \Drupal::database();

    $database->delete('darts')
      ->condition('id', $id)
      ->execute();
}

function darts_delete_last_score_of_game($gameid) {

    $database = \Drupal::database();
    $query = $database->select('darts_game', 'd');
    $query
    ->fields('d', [])
    ->condition('d.gameid', $gameid)
    ->orderBy('d.id', 'DESC')
    ->range(0, 1);

    $results = $query->execute()->fetchAll();

    $lastid = $results[0]->id;

    
    $database = \Drupal::database();

    $database->delete('darts_game')
      ->condition('id', $lastid)
      ->execute();
    
}

function darts_get_game($uid, $gameid) {
    $database = \Drupal::database();
    $query = $database->select('darts', 'd');
    $query
    ->fields('d', array('gameid'))
    ->condition('d.uid', $uid);

    $results = $query->execute()->fetchAll();

    return $results;
}

function darts_player_already_there($array, $player) {
    foreach ($array as $val) {
        if ($val['player'] == $player) {
            return true;
        }
    }

    return false;
}

function darts_stats_180() {
    $players = Player::getPlayers();

    $database = \Drupal::database();
    $query = $database->select('darts', 'd');
    $query
    ->fields('d')
    ->orderBy('d.uid', 'DESC')
    ->orderBy('d.gameid', 'DESC')
    ->orderBy('d.id', 'ASC');

    $results = $query->execute()->fetchAll();

    $games = [];
    foreach ($results as $row) {
      $games[$row->uid][$row->gameid]['score'][] = [
        'point' => $row->score,
        'created' => $row->created,
      ];

    }

    $stats = [];
    $stat = [];
    foreach ($games as $uuid => $game) {

        if ($uuid == 0) {
            continue;
        }
      
        foreach ($game as $gameid => $onegame) {
       
            foreach ($onegame as $round) {
                foreach ($round as $throw) {
                    if ($throw['point'] == 180) {
                        if (!isset($stat[$uuid])) {
                            $stat[$uuid] = [
                                'point' => '',
                                'player' => $players[$uuid],
                                'created' => $throw['created'],
                            ];
                        }
                        if (!isset($stat[$uuid]['value'])) {
                            $stat[$uuid]['value'] = 1;
                        } else {
                            $stat[$uuid]['value']++;
                        }
                    }
                }
            }
        }
        
            
        
    }

    dpm($stat);
    usort($stat, function($a, $b) {
      return $b['value'] <=> $a['value'];
    });

    $stats['180'] = [
                'label' => 'OOOONE HUNDREEEEED AND EIGHTYEEEEEE',
                'stat' => $stat,
              ];

    dpm($stats);

    return $stats;
}

function darts_parse_game_data() {
    $database = \Drupal::database();
    $query = $database->select('darts', 'd');
    $query
    ->fields('d')
    ->orderBy('d.uid', 'DESC')
    ->orderBy('d.gameid', 'DESC')
    ->orderBy('d.id', 'ASC');

    $results = $query->execute()->fetchAll();

    $games = [];
    foreach ($results as $row) {
      $games[$row->uid][$row->gameid]['score'][] = [
        'point' => $row->score,
        'created' => $row->created,
      ];

    }

    return $games;
}

function darts_stats_best_average() {
    $players = Player::getPlayers();

    $games = darts_parse_game_data();

    $stats = [];
    $stat = [];
    foreach ($games as $uuid => $game) {

        if ($uuid == 0) {
            continue;
        }
      
      foreach ($game as $gameid => $onegame) {

        // Find best avarage.
        foreach ($onegame as $round) {

          $i = 0;
          $sum = 0;  
          foreach ($round as $throw) {
            $i++;
            $sum += $throw['point'];
          }

          if ($i == 17) {
              $averages[] = [
                'point' => $sum . ' pont',
                'value' => number_format(round($sum / $i * 100) / 100, 2, '.', ''),
                'player' => $players[$uuid],
                'created' => $throw['created'],
              ];
          }
        }

      }

    }
    
    usort($averages, function($a, $b) {
      return $b['value'] <=> $a['value'];
    });

    $i = 0;
    foreach ($averages as $average) {

        if (!darts_player_already_there($stat, $average['player'])) {
            $stat[] = $average;

            $i++;
            if ($i > 9) {
                break;
            }
        }

    }

    $stats['best_average'] = [
        'label' => 'Legjobb átlag',
        'stat' => $stat,
    ];

    return $stats;
}

function darts_stats_best_first9() {
    $players = Player::getPlayers();

    $games = darts_parse_game_data();

    $stats = [];
    $stat = [];
    foreach ($games as $uuid => $game) {

        if ($uuid == 0) {
            continue;
        }
      
      foreach ($game as $gameid => $onegame) {

        // Find best avarage.
        foreach ($onegame as $round) {

          $i = 0;
          $sum = 0;  
          foreach ($round as $throw) {
            $i++;
            $sum += $throw['point'];
            if ($i == 3) {
                break;
            }
          }


          $averages[] = [
            'point' => $sum . ' pont',
            'value' => number_format(round($sum / $i * 100) / 100, 2, '.', ''),
            'player' => $players[$uuid],
            'created' => $throw['created'],
          ];
        }

      }

    }
    
    usort($averages, function($a, $b) {
      return $b['value'] <=> $a['value'];
    });


    $i = 0;
    foreach ($averages as $average) {
        

        if (!darts_player_already_there($stat, $average['player'])) {
            $stat[] = $average;

            $i++;
            if ($i > 5) {
                break;
            }
        }

    }

    $stats['first_nine'] = [
        'label' => 'Legjobb első 9 nyíl',
        'stat' => $stat,
    ];

    return $stats;
}


function darts_stats_hard_working() {
    $players = Player::getPlayers();

    $games = darts_parse_game_data();

    $stats = [];
    $stat = [];
    foreach ($games as $uuid => $game) {
        if ($uuid == 0) {
            continue;
        }

          $averages[] = [
            'point' => '',
            'value' => count($game),
            'player' => $players[$uuid],
            'created' => '',
            'suffix' => 'meccs',
          ];
    }
    
    usort($averages, function($a, $b) {
      return $b['value'] <=> $a['value'];
    });


    $i = 0;
    foreach ($averages as $average) {
      $i++;
      if ($i > 5) {
        break;
      }

      $stat[] = $average;

      $stats['hard_worker'] = [
        'label' => 'Iparkodók',
        'stat' => $stat,
      ];

    }

    return $stats;
}

function darts_stats_last_game_date() {
    $players = Player::getPlayers();

    $games = darts_parse_game_data();

    $stats = [];
    $stat = [];
    foreach ($games as $uuid => $game) {
        if ($uuid == 0) {
            continue;
        }

        foreach ($game as $gameid => $onegame) {

            foreach ($onegame as $round) {

                foreach ($round as $throw) {
                    if (!isset($last[$uuid])) {
                       $last[$uuid] = [
                            'player' => $players[$uuid],
                            'value' => $throw['created'],
                        ];    
                    } else {
                        if ($throw['created'] > $last[$uuid]['value']) {
                            $last[$uuid] = [
                                'player' => $players[$uuid],
                                'value' => $throw['created'],
                            ];
                        }
                    }
                }
            }
        }
    }

    usort($last, function($a, $b) {

      return $b['value'] <=> $a['value'];
    });

    foreach ($last as &$val) {

        $val['value'] = date('Y-m-d', $val['value']);
    }

    $stats['last_game_date'] = [
        'label' => 'Utolsó edzés',
        'stat' => $last,
      ];

    return $stats;
}

function darts_get_last_game_gameid() {
    $database = \Drupal::database();
    $query = $database->select('darts_game', 'd');
    $query
    ->fields('d', array('gameid'))
    ->orderBy('d.gameid', 'DESC')
    ->range(0, 1);

    $results = $query->execute()->fetchAll();

    return $results;
}

function darts_game_write_score($uid, $gameid, $score) {
    $database = \Drupal::database();
    $result = $database->insert('darts_game')
      ->fields([
        'uid' => $uid,
        'gameid' => $gameid,
        'score' => $score,
        'created' => \Drupal::time()->getRequestTime(),
      ])
    ->execute();

    return $result;
}

function darts_get_game_players($gameid) {
    $database = \Drupal::database();
    $query = $database->select('darts_game', 'g');
    $query
    ->fields('g', [])
    ->condition('g.gameid', $gameid)
    ->orderBy('g.created', 'DESC');

    $results = $query->execute()->fetchAll();

    $players = [];
    foreach ($results as $row) {
        if (!in_array($row->uid, $players)) {
            $players[] = $row->uid;

            if (count($players) == 2) {
                return $players;
            }
        }
    }
}

function darts_get_game_players_name($uids) {
    $players = Player::getPlayers();

    foreach ($uids as $uid) {
        $names[] = $players[$uid];
    }

    return $names;
}

function darts_get_game_data_former() {

    $player_names = Player::getPlayers();

    $database = \Drupal::database();
    $query = $database->select('darts_game', 'g');
    $query
    ->fields('g', [])
    ->orderBy('g.gameid', 'DESC')
    ->orderBy('g.id', 'DESC');

    $results = $query->execute()->fetchAll();

    $data = [];
    $player = [];
    $set = 1;
    $currentgame = 0;
    foreach ($results as $row) {
        $date = date('Y-m-d', $row->created);

        $players = darts_get_game_players($row->gameid);
        $data[$date][$row->gameid]['players'] = darts_get_game_players_name($players);

        if ($currentgame !== $row->gameid) {
            $player = [];
            $set = 1;
            $data[$date][$row->gameid]['winner'] = $player_names[$row->uid];
        }


        
        $data[$date][$row->gameid]['data'][$set][$row->id][$player_names[$row->uid]] = $row->score;
        if (!isset($player[$row->uid])) {

            foreach ($players as $playerid) {
                $player[$playerid] = 501 - $row->score;
            }
        } else {
            $player[$row->uid] -= $row->score;

            if ($player[$row->uid] == 0) {
                $data[$date][$row->gameid]['data'][$set]['winner'] = $player_names[$row->uid];
                $set++;



                foreach ($players as $playerid) {
                    unset($player[$playerid]);
                }
            }
        }

        $currentgame = $row->gameid;


    }

    dpm($results);
    dpm($data);

    return $data;
}

function darts_get_games($day) {

    if ($day == '') {
        return [];
    }

    $from = strtotime($day . ' 00:00:01');
    $to = strtotime($day . ' 00:00:01' . ' +1 day');

    $database = \Drupal::database();
    $query = $database->select('darts_game', 'g');
    $query
    ->fields('g', ['gameid'])
    ->orderBy('g.gameid', 'ASC')
    ->condition('g.created', $from, '>')
    ->condition('g.created', $to, '<');

    $results = $query->distinct()->execute()->fetchCol();
    //$results = [20];

    $games = [];
    foreach ($results as $gameid) {
        $games[] = new Game($gameid);
    }

    return $games;
}


function darts_cmp($a, $b) {
    return $a->score < $b->score;
}

function darts_cmp_array($a, $b) {
    return $a['score'] < $b['score'];
}

function darts_get_gameday_highlights($games) {
    foreach ($games as $game) {
        foreach ($game->legs as $leg) {
            foreach ($leg->throws as $throw) {
                $throws[] = $throw;
            }
        }
    }

    usort($throws, 'darts_cmp');

}

function darts_list_gamedays() {
    $database = \Drupal::database();
    $query = $database->select('darts_game', 'g');
    $query
    ->fields('g', ['created']);

    $results = $query->execute()->fetchAll();

    $days = [];
    foreach ($results as $row) {
        $days[date('Y-m-d', $row->created)] = date('Y-m-d', $row->created);
    }

    return $days;
}

function game_draw_add_player($did, $team, $uid) {
    $database = \Drupal::database();
    $query = $database->select('darts_matrix', 'm');
    $query
    ->fields('m', ['data'])
    ->condition('m.id', $id);

    $results = $query->execute()->fetchAll();

    $teams = unserialize($results[0]->data);
}

function get_users_general_avg() {

    $database = \Drupal::database();

    $query = $database->select('darts', 'd');
    $query
    ->fields('d')
    ->groupBy('uid');
    $query->addExpression('AVG(score)');

    $results = $query->execute()->fetchAll();

    $genavg = [];
    foreach ($results as $row) {
        $genavg[$row->uid] = ceil($row->expression);
    }

    return $genavg;

}

function darts_double_map() {
    return ['170' => ['T20','T20','DB'],
    '167' => ['T20','T19','DB'],
    '164' => ['T20','T18','DB'],
    '161' => ['T20','T17','DB'],
    '160' => ['T20','T20','D20'],
    '158' => ['T20','T20','D19'],
    '157' => ['T20','T19','D20'],
    '156' => ['T20','T20','D18'],
    '155' => ['T20','T15','DB'],
    '154' => ['T20','T18','D20'],
    '153' => ['T20','T19','D18'],
    '152' => ['T20','T20','D16'],
    '151' => ['T20','T17','D20'],
    '150' => ['T20','T18','D18'],
    '149' => ['T20','T19','D16'],
    '148' => ['T20','T16','D20'],
    '147' => ['T20','T17','D18'],
    '146' => ['T20','T18','D16'],
    '145' => ['T20','T15','D20'],
    '144' => ['T20','T20','D12'],
    '143' => ['T20','T17','D16'],
    '142' => ['T20','T14','D20'],
    '141' => ['T20','T15','D18'],
    '140' => ['T20','T16','D16'],
    '139' => ['T20','T13','D20'],
    '138' => ['T20','T14','D18'],
    '137' => ['T17','T18','D16'],
    '136' => ['T20','T20','D8'],
    '135' => ['T20','T15','D15'],
    '134' => ['T20','T14','D16'],
    '133' => ['T20','T19','D8'],
    '132' => ['T20','T20','D6'],
    '131' => ['T20','T13','D16'],
    '130' => ['T20','T18','D8'],
    '129' => ['T20','T19','D6'],
    '128' => ['T18','T14','D16'],
    '127' => ['T19','T18','D8'],
    '126' => ['T19','T19','D6'],
    '125' => ['B','T20','D20'],
    '124' => ['T20','D16','D16'],
    '123' => ['T19','T16','D9'],
    '122' => ['T18','T20','D4'],
    '121' => ['T20','T15','D8'],
    '120' => ['T20','20','D20'],
    '119' => ['T19','T10','D16'],
    '118' => ['T20','18','D20'],
    '117' => ['T20','17','D20'],
    '116' => ['T20','16','D20'],
    '115' => ['T20','15','D20'],
    '114' => ['T20','14','D20'],
    '113' => ['T20','13','D20'],
    '112' => ['T20','20','D16'],
    '112' => ['T20','12','D20'],
    '111' => ['T20','19','D16'],
    '110' => ['T20','18','D16'],
    '109' => ['T20','17','D16'],
    '108' => ['T20','16','D16'],
    '107' => ['T19','18','D16'],
    '106' => ['T20','14','D16'],
    '105' => ['T20','13','D16'],
    '104' => ['T18','18','D16'],
    '103' => ['T20','11','D16'],
    '102' => ['T20','10','D16'],
    '101' => ['T17','18','D16'],
    '100' => ['T20','D20'],
    '99' => ['T19','10','D16'],
    '98' => ['T20','D19'],
    '97' => ['T19','D20'],
    '96' => ['T20','D18'],
    '95' => ['T15','18','D16'],
    '94' => ['T18','D20'],
    '93' => ['T19','D18'],
    '92' => ['T20','D16'],
    '91' => ['T17','D20'],
    '90' => ['T18','D18'],
    '89' => ['T19','D16'],
    '88' => ['T16','D20'],
    '87' => ['T17','D18'],
    '86' => ['T18','D16'],
    '85' => ['T15','D20'],
    '84' => ['T20','D12'],
    '83' => ['T17','D16'],
    '82' => ['T14','D20'],
    '81' => ['T15','D18'],
    '80' => ['T16','D16'],
    '79' => ['T13','D20'],
    '78' => ['T14','D18'],
    '77' => ['T15','D16'],
    '76' => ['T20','D8'],
    '75' => ['T15','D15'],
    '74' => ['T14','D16'],
    '73' => ['T19','D8'],
    '72' => ['T20','D6'],
    '71' => ['T13','D16'],
    '70' => ['T18','D8'],
    '69' => ['T19','D6'],
    '68' => ['T16','D10'],
    '67' => ['T17','D8'],
    '66' => ['T10','D18'],
    '65' => ['T15','D10'],
    '64' => ['D16','D16'],
    '63' => ['T13','D12'],
    '62' => ['T10','D16'],
    '61' => ['T15','D8'],
    '60' => ['20','D20'],
    '59' => ['19','D20'],
    '58' => ['18','D20'],
    '57' => ['17','D20'],
    '56' => ['16','D20'],
    '55' => ['15','D20'],
    '54' => ['14','D20'],
    '53' => ['13','D20'],
    '52' => ['20','D16'],
    '51' => ['19','D16'],
    '50' => ['18','D16'],
    '50' => ['DB'],
    '49' => ['17','D16'],
    '48' => ['16','D16'],
    '47' => ['15','D16'],
    '46' => ['14','D16'],
    '45' => ['13','D16'],
    '44' => ['12','D16'],
    '43' => ['11','D16'],
    '42' => ['10','D16'],
    '41' => ['9','D16'],
    '40' => ['D20'],
];


}